services:
  db:
    container_name: mysql_playground_db
    image: mysql:latest
    restart: always
    env_file:
      - ./.env.local
    ports:
      - "3640:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  pma:
    container_name: mysql_playground_pma
    image: phpmyadmin:latest
    restart: always
    environment:
      UPLOAD_LIMIT: 950M
    ports:
      - "8895:80"
    links:
      - db
    ###> symfony/mailer ###
  mailer:
      image: axllent/mailpit
      ports:
          - "1025"
          - "8025"
      environment:
          MP_SMTP_AUTH_ACCEPT_ANY: 1
          MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
